name = "CFD2d"
uuid = "2eaf6843-ad83-451b-af76-a2199a21de4f"
authors = ["T.Hashimoto <tkrhsmt@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
